### ISSUE TITLE
Integrate into fastlane

### ISSUE THREAD

**Issue by hjanuschka** [Mindera/fastlane-plugin-cosigner#8]
Hey @p4checo 🤝 

we recently integrated one of my plugins into fastlane `automatic_code_signing` for setting team_id and signing mode (manual, auto).

your plugin looks super awesome, how about combining forces and integrating the differences/missing-parts into the core action - providing all fastlane users a smooth way to handle codesigning?

namely:
  * setting CODE_SIGN_IDENTITY if `:code_sign_identity` set
  * setting PROVISIONING_PROFILE_SPECIFIER  if `:profile_name` set
  * setting PROVISIONING_PROFILE  if `:profile_uuid` set
  * setting PRODUCT_BUNDLE_IDENTIFIER if `bundle_identifier` set

for easy backward compatibility - we can add aliases and even transform parameters in `alias_used`
let me know if that is something you might wan't to do, if you need help anywhere let me know.

Here is the action i am talking about:
  * https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/automatic_code_signing.rb

once you have a PR - feel free to directly mention me, and i am going to review it. 👍 

regards ✋

**Comment by p4checo** [comment]
Hi @hjanuschka! 🙌 

That's a really good idea. We would definitely be interested in providing `cosigner`'s functionalities to all fastlane users! cc @portellaa 

We initially proposed a new action, but @KrauseFx suggested we create a plugin (fastlane/fastlane#7136). It began being called `force_sign` but was renamed to `cosigner` afterwards. Guess it will end up in an action after all! 💪   The thing we are most sad about is leaving the name `cosigner` behind... 😢 

We'll look into this as soon as we have some time, and will mention you once we open the PR 😉 

Cheers! 🍻

**Comment by hjanuschka** [comment]
let me know if you need something! - we could use `cosigner` as an alias (although need to use some symbol checking for users that have the plugin loaded)

**Comment by KrauseFx** [comment]
Yeah, so we do add new actions, by migrating successful plugins into the fastlane main code base. This is what happened to the widely used plugin by @hjanuschka 👍

**Comment by p4checo** [comment]
Thanks for the explanation! Makes total sense 😉

**Comment by p4checo** [comment]
🚀

**Comment by KrauseFx** [comment]
Thanks everyone ❤️
